algo = input('Digite algo: ')
print("o tipo primitivo desse valor é ",type(algo))
print('algo é numerico? ', algo.isnumeric())
print('algo é alfabetico? ', algo.isalpha())
print('algo é alfaNumerico? ', algo.isalnum())
print('algo é Printavel? ', algo.isprintable())
print('aLgo é maiuscula? ', algo.isupper())
print('algo é minuscula? ', algo.islower())
print('Algo só tem espaço? ', algo.isspace())